name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Ensure that Node.js version 14 is compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Make sure this command generates the correct output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Ensure this is the correct path to your build output
