name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Replace with your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14" # Use your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build # Adjust if your build script is named differently

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
